version: 1
kind: DeviceProfile
name: "Default"
description: "Controller-Box built-in gamepad identity profile"
mapping:
  - name: "A"
    source_event:
      gamepad:
        button: A
    target_events:
      - gamepad: A
  - name: "B"
    source_event:
      gamepad:
        button: B
    target_events:
      - gamepad: B
  - name: "D-Pad Up"
    source_event:
      gamepad:
        button: Up
    target_events:
      - gamepad: Up
  - name: "D-Pad Down"
    source_event:
      gamepad:
        button: Down
    target_events:
      - gamepad: Down
  - name: "D-Pad Left"
    source_event:
      gamepad:
        button: Left
    target_events:
      - gamepad: Left
  - name: "D-Pad Right"
    source_event:
      gamepad:
        button: Right
    target_events:
      - gamepad: Right
