# CMake generated Testfile for 
# Source directory: /workspace/project
# Build directory: /workspace/project/.diag-prefix-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smoke_test_sdl2 "/workspace/project/.diag-prefix-build/smoke_test_sdl2")
set_tests_properties(smoke_test_sdl2 PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;15;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(smoke_test_nanosvg "/workspace/project/.diag-prefix-build/smoke_test_nanosvg")
set_tests_properties(smoke_test_nanosvg PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;16;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_kernel_controller "/workspace/project/tests/run-kernel-controller-test.sh" "/workspace/project/.diag-prefix-build/test_kernel_controller" "/workspace/project/.diag-prefix-build")
set_tests_properties(test_kernel_controller PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;27;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_flatpak_manifest "/nix/store/gxzhl7aaiid7zp3y47jqqiq7zg5mqpwp-python3-3.14.6/bin/python3.14" "/workspace/project/tests/test_flatpak_manifest.py")
set_tests_properties(test_flatpak_manifest PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;44;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_packaging "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test_packaging.sh" "/workspace/project/.diag-prefix-build")
set_tests_properties(test_packaging PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;59;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_installed_smoke "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test_installed_smoke.sh" "/workspace/project/.diag-prefix-build")
set_tests_properties(test_installed_smoke PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;72;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_installed_diagram "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test_installed_diagram.sh" "/workspace/project/.diag-prefix-build")
set_tests_properties(test_installed_diagram PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;81;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_installed_functional_evidence "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-installed-functional-evidence.sh" "/workspace/project")
set_tests_properties(test_installed_functional_evidence PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;87;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_factory_environment "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-factory-environment.sh")
set_tests_properties(test_factory_environment PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;91;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_factory_runner "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-factory-runner.sh")
set_tests_properties(test_factory_runner PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;94;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_campaign_audit "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-campaign-audit.sh")
set_tests_properties(test_campaign_audit PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;97;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_ralph_campaign "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-ralph-campaign.sh")
set_tests_properties(test_ralph_campaign PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;100;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_ralph_stale_recovery "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-ralph-stale-recovery.sh")
set_tests_properties(test_ralph_stale_recovery PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;103;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_ralph_recover_safety "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-ralph-recover-safety.sh")
set_tests_properties(test_ralph_recover_safety PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;106;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_pi2_ollama_wrapper "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-pi2-ollama-wrapper.sh")
set_tests_properties(test_pi2_ollama_wrapper PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;109;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_installed_binary "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test_installed_binary.sh" "/workspace/project/.diag-prefix-build")
set_tests_properties(test_installed_binary PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;118;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_controller_production_routing_probe "/nix/store/bwry105g7v5jspr41bx9x3fcfqsmfkq2-bash-interactive-5.3p15/bin/bash" "/workspace/project/tests/test-controller-production-routing-probe.sh")
set_tests_properties(test_controller_production_routing_probe PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;130;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_sample "/workspace/project/.diag-prefix-build/test_sample")
set_tests_properties(test_sample PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;179;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_sdl_dummy "/workspace/project/.diag-prefix-build/test_sdl_dummy")
set_tests_properties(test_sdl_dummy PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;180;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_config_paths "/workspace/project/.diag-prefix-build/test_config_paths")
set_tests_properties(test_config_paths PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;181;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_font_path "/workspace/project/.diag-prefix-build/test_font_path")
set_tests_properties(test_font_path PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;188;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_settings "/workspace/project/.diag-prefix-build/test_settings")
set_tests_properties(test_settings PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;189;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_assignments "/workspace/project/.diag-prefix-build/test_assignments")
set_tests_properties(test_assignments PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;190;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_profile_yaml "/workspace/project/.diag-prefix-build/test_profile_yaml")
set_tests_properties(test_profile_yaml PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;197;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_profile_list "/workspace/project/.diag-prefix-build/test_profile_list")
set_tests_properties(test_profile_list PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;206;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_connection "/workspace/project/.diag-prefix-build/test_connection")
set_tests_properties(test_connection PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;213;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_objectmanager_parse "/workspace/project/.diag-prefix-build/test_objectmanager_parse")
set_tests_properties(test_objectmanager_parse PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;220;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_hotplug "/workspace/project/.diag-prefix-build/test_hotplug")
set_tests_properties(test_hotplug PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;227;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_properties_changed "/workspace/project/.diag-prefix-build/test_properties_changed")
set_tests_properties(test_properties_changed PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;234;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_calls "/workspace/project/.diag-prefix-build/test_manager_calls")
set_tests_properties(test_manager_calls PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;242;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_composite_calls "/workspace/project/.diag-prefix-build/test_composite_calls")
set_tests_properties(test_composite_calls PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;252;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_intercept_poll "/workspace/project/.diag-prefix-build/test_intercept_poll")
set_tests_properties(test_intercept_poll PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;260;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_source_props "/workspace/project/.diag-prefix-build/test_source_props")
set_tests_properties(test_source_props PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;268;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_target_props "/workspace/project/.diag-prefix-build/test_target_props")
set_tests_properties(test_target_props PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;274;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_input_signal "/workspace/project/.diag-prefix-build/test_input_signal")
set_tests_properties(test_input_signal PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;282;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_create_composite "/workspace/project/.diag-prefix-build/test_create_composite")
set_tests_properties(test_create_composite PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;289;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_gamepad_order "/workspace/project/.diag-prefix-build/test_gamepad_order")
set_tests_properties(test_gamepad_order PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;294;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_icon_map "/workspace/project/.diag-prefix-build/test_icon_map")
set_tests_properties(test_icon_map PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;305;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_icon_cache "/workspace/project/.diag-prefix-build/test_icon_cache")
set_tests_properties(test_icon_cache PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;313;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_icon_lookup "/workspace/project/.diag-prefix-build/test_icon_lookup")
set_tests_properties(test_icon_lookup PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;323;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_renderer_init "/workspace/project/.diag-prefix-build/test_renderer_init")
set_tests_properties(test_renderer_init PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;330;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_text "/workspace/project/.diag-prefix-build/test_text")
set_tests_properties(test_text PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;351;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_font_init "/workspace/project/.diag-prefix-build/test_font_init")
set_tests_properties(test_font_init PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;363;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_widgets "/workspace/project/.diag-prefix-build/test_widgets")
set_tests_properties(test_widgets PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;372;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_widget_list "/workspace/project/.diag-prefix-build/test_widget_list")
set_tests_properties(test_widget_list PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;381;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_widget_grid "/workspace/project/.diag-prefix-build/test_widget_grid")
set_tests_properties(test_widget_grid PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;387;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_widget_tabbar "/workspace/project/.diag-prefix-build/test_widget_tabbar")
set_tests_properties(test_widget_tabbar PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;395;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_widget_progress "/workspace/project/.diag-prefix-build/test_widget_progress")
set_tests_properties(test_widget_progress PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;401;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_focus "/workspace/project/.diag-prefix-build/test_focus")
set_tests_properties(test_focus PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;408;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_input_map "/workspace/project/.diag-prefix-build/test_input_map")
set_tests_properties(test_input_map PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;412;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_animation "/workspace/project/.diag-prefix-build/test_animation")
set_tests_properties(test_animation PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;417;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_surface_build "/workspace/project/.diag-prefix-build/test_surface_build")
set_tests_properties(test_surface_build PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;424;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_overlay_lifecycle "/workspace/project/.diag-prefix-build/test_overlay_lifecycle")
set_tests_properties(test_overlay_lifecycle PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;431;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_identity "/workspace/project/.diag-prefix-build/test_identity")
set_tests_properties(test_identity PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;436;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_assign "/workspace/project/.diag-prefix-build/test_assign")
set_tests_properties(test_assign PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;440;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_assign_persist "/workspace/project/.diag-prefix-build/test_assign_persist")
set_tests_properties(test_assign_persist PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;444;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_identity_downgrade "/workspace/project/.diag-prefix-build/test_identity_downgrade")
set_tests_properties(test_identity_downgrade PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;448;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_order_restore "/workspace/project/.diag-prefix-build/test_order_restore")
set_tests_properties(test_order_restore PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;452;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_grid_render "/workspace/project/.diag-prefix-build/test_grid_render")
set_tests_properties(test_grid_render PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;457;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_player_mode "/workspace/project/.diag-prefix-build/test_player_mode")
set_tests_properties(test_player_mode PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;463;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_host_mode "/workspace/project/.diag-prefix-build/test_host_mode")
set_tests_properties(test_host_mode PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;467;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_conflict "/workspace/project/.diag-prefix-build/test_conflict")
set_tests_properties(test_conflict PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;471;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_overlay_visual "/workspace/project/.diag-prefix-build/test_overlay_visual")
set_tests_properties(test_overlay_visual PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;480;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_profile_cycle "/workspace/project/.diag-prefix-build/test_profile_cycle")
set_tests_properties(test_profile_cycle PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;487;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_dynamic_columns "/workspace/project/.diag-prefix-build/test_dynamic_columns")
set_tests_properties(test_dynamic_columns PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;491;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_trigger "/workspace/project/.diag-prefix-build/test_trigger")
set_tests_properties(test_trigger PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;496;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_close "/workspace/project/.diag-prefix-build/test_close")
set_tests_properties(test_close PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;500;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_overlay_integration "/workspace/project/.diag-prefix-build/test_overlay_integration")
set_tests_properties(test_overlay_integration PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;507;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_tabs "/workspace/project/.diag-prefix-build/test_manager_tabs")
set_tests_properties(test_manager_tabs PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;519;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_controllers_tab "/workspace/project/.diag-prefix-build/test_controllers_tab")
set_tests_properties(test_controllers_tab PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;527;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_profiles_tab "/workspace/project/.diag-prefix-build/test_profiles_tab")
set_tests_properties(test_profiles_tab PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;535;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_profile_diagram "/workspace/project/.diag-prefix-build/test_profile_diagram")
set_tests_properties(test_profile_diagram PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;542;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_editor_list_mode "/workspace/project/.diag-prefix-build/test_editor_list_mode")
set_tests_properties(test_editor_list_mode PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;549;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_profile_validate "/workspace/project/.diag-prefix-build/test_profile_validate")
set_tests_properties(test_profile_validate PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;556;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_editor_seq_mode "/workspace/project/.diag-prefix-build/test_editor_seq_mode")
set_tests_properties(test_editor_seq_mode PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;561;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_profile_save "/workspace/project/.diag-prefix-build/test_profile_save")
set_tests_properties(test_profile_save PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;568;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_settings_tab "/workspace/project/.diag-prefix-build/test_settings_tab")
set_tests_properties(test_settings_tab PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;573;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_service_install "/workspace/project/.diag-prefix-build/test_service_install")
set_tests_properties(test_service_install PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;580;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_integration "/workspace/project/.diag-prefix-build/test_manager_integration")
set_tests_properties(test_manager_integration PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;585;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_production "/workspace/project/.diag-prefix-build/test_manager_production")
set_tests_properties(test_manager_production PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;593;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_fb_assert "/workspace/project/.diag-prefix-build/test_fb_assert")
set_tests_properties(test_fb_assert PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;602;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_dbus_inject "/workspace/project/.diag-prefix-build/test_manager_dbus_inject")
set_tests_properties(test_manager_dbus_inject PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;612;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_visual "/workspace/project/.diag-prefix-build/test_manager_visual")
set_tests_properties(test_manager_visual PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;621;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_overlay_service "/workspace/project/.diag-prefix-build/test_overlay_service")
set_tests_properties(test_overlay_service PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;629;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_overlay_interaction "/workspace/project/.diag-prefix-build/test_overlay_interaction")
set_tests_properties(test_overlay_interaction PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;636;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_overlay_latency "/workspace/project/.diag-prefix-build/test_overlay_latency")
set_tests_properties(test_overlay_latency PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;643;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_daemon_footprint "/workspace/project/.diag-prefix-build/test_daemon_footprint")
set_tests_properties(test_daemon_footprint PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;650;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_overlay_reconcile "/workspace/project/.diag-prefix-build/test_overlay_reconcile")
set_tests_properties(test_overlay_reconcile PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;657;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_golden "/workspace/project/.diag-prefix-build/test_golden")
set_tests_properties(test_golden PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;668;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_backend_smoke "/workspace/project/.diag-prefix-build/test_backend_smoke")
set_tests_properties(test_backend_smoke PROPERTIES  SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;680;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_backend_smoke_sw "/workspace/project/.diag-prefix-build/test_backend_smoke_sw")
set_tests_properties(test_backend_smoke_sw PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;693;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_interaction_inventory "/workspace/project/.diag-prefix-build/test_interaction_inventory")
set_tests_properties(test_interaction_inventory PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;704;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_native_dbus "/workspace/project/.diag-prefix-build/test_native_dbus")
set_tests_properties(test_native_dbus PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;714;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_dbus_signatures "/workspace/project/.diag-prefix-build/test_dbus_signatures")
set_tests_properties(test_dbus_signatures PROPERTIES  _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;718;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_installed_functional "/workspace/project/.diag-prefix-build/test_installed_functional")
set_tests_properties(test_installed_functional PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;731;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_overlay_native "/workspace/project/.diag-prefix-build/test_overlay_native")
set_tests_properties(test_overlay_native PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;744;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_interaction_ctrl "/workspace/project/.diag-prefix-build/test_manager_interaction_ctrl")
set_tests_properties(test_manager_interaction_ctrl PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;753;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_interaction_prof "/workspace/project/.diag-prefix-build/test_manager_interaction_prof")
set_tests_properties(test_manager_interaction_prof PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;762;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_native "/workspace/project/.diag-prefix-build/test_manager_native")
set_tests_properties(test_manager_native PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;774;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
add_test(test_manager_native_prof "/workspace/project/.diag-prefix-build/test_manager_native_prof")
set_tests_properties(test_manager_native_prof PROPERTIES  ENVIRONMENT "SDL_VIDEODRIVER=dummy" _BACKTRACE_TRIPLES "/workspace/project/tests/CMakeLists.txt;782;add_test;/workspace/project/tests/CMakeLists.txt;0;;/workspace/project/CMakeLists.txt;198;include;/workspace/project/CMakeLists.txt;0;")
