/*
 * icon_lookup.c — Runtime icon lookup API (SPEC §8.4, §8.5).
 *
 * Resolves a device type string + optional profile icon override to an
 * SDL2 texture and display label.  Uses the icon cache for SVG lookups
 * and SDL2_image for custom PNG files at absolute paths.
 *
 * Security: absolute icon paths from profile sidecars are validated
 * against `..` traversal and canonicalized via realpath() before loading.
 * Only paths within safe directories (user config, user data, system data)
 * are accepted.
 */
#include "icons/icon_lookup.h"

/* For config path resolution (safe directory checks). */
#include "config/config_paths.h"
/* Generated by CMake: DATA_DIR, etc. */
#include "config.h"

#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>

#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef PATH_MAX
#define PATH_MAX 4096
#endif

/* ------------------------------------------------------------------ */
/*  Path validation                                                   */
/* ------------------------------------------------------------------ */

/*
 * Check if a path contains a ".." component (traversal attempt).
 * We scan for "/.." at any position, as well as ".." at the start.
 * Returns true if the path is safe (no traversal), false otherwise.
 */
static bool path_is_safe(const char *path)
{
    if (!path || path[0] == '\0')
        return false;

    /* Reject ".." as first component. */
    if (path[0] == '.' && path[1] == '.') {
        if (path[2] == '\0' || path[2] == '/')
            return false;
    }

    /* Scan for "/.." anywhere in the path. */
    const char *p = path;
    while ((p = strstr(p, "/..")) != NULL) {
        /* Ensure it's a full component: followed by '/', NUL, or
         * nothing.  "/../" or "/..\0" → traversal. */
        char c = p[3];
        if (c == '\0' || c == '/')
            return false;
        p++;   /* continue scanning past this match */
    }

    return true;
}

/*
 * Check if resolved_path is within base_dir.
 * Both must be canonical (realpath'd) absolute paths.
 * Returns true if resolved_path starts with base_dir + "/" or equals base_dir.
 */
static bool path_within(const char *resolved_path, const char *base_dir)
{
    size_t base_len = strlen(base_dir);
    if (strncmp(resolved_path, base_dir, base_len) != 0)
        return false;

    /* Exact match or subdirectory boundary. */
    if (resolved_path[base_len] == '\0' || resolved_path[base_len] == '/')
        return true;

    return false;
}

int cbx_icon_validate_path(const char *abs_path,
                            char *resolved, size_t resolved_size)
{
    if (!abs_path || abs_path[0] == '\0')
        return -EINVAL;

    /* Must be absolute. */
    if (abs_path[0] != '/')
        return -EINVAL;

    /* Reject ".." traversal. */
    if (!path_is_safe(abs_path))
        return -EINVAL;

    /* Canonicalize via realpath(). */
    char rp[PATH_MAX];
    if (!realpath(abs_path, rp))
        return -EACCES;

    /* Check the canonical path is still safe (realpath could resolve
     * symlinks to unexpected locations, but we already rejected ".."
     * and realpath gives us the true path — we just need to check
     * it's within a safe directory). */
    if (!path_is_safe(rp))
        return -EACCES;

    /* Determine safe directories. */
    char user_config_dir[PATH_MAX];
    char user_data_dir[PATH_MAX];

    int rc = cbx_resolve_config_dir(user_config_dir, sizeof(user_config_dir));
    bool in_safe_dir = false;

    if (rc == 0 && path_within(rp, user_config_dir))
        in_safe_dir = true;

    if (!in_safe_dir) {
        rc = cbx_resolve_user_profiles_dir(user_data_dir, sizeof(user_data_dir));
        if (rc == 0 && path_within(rp, user_data_dir))
            in_safe_dir = true;
    }

    if (!in_safe_dir) {
        /* System data dir (/usr/share/controller-box). */
        const char *sys_data = cbx_data_dir();
        if (sys_data && path_within(rp, sys_data))
            in_safe_dir = true;
    }

    if (!in_safe_dir) {
        /* System InputPlumber data dir (/usr/share/inputplumber). */
        const char *ip_data = cbx_system_inputplumber_dir();
        if (ip_data && path_within(rp, ip_data))
            in_safe_dir = true;
    }

    if (!in_safe_dir)
        return -EACCES;

    /* Copy resolved path to output if requested. */
    if (resolved && resolved_size > 0) {
        if (strlen(rp) >= resolved_size)
            return -ENAMETOOLONG;
        snprintf(resolved, resolved_size, "%s", rp);
    }

    return 0;
}

/* ------------------------------------------------------------------ */
/*  PNG loading via SDL2_image                                         */
/* ------------------------------------------------------------------ */

/*
 * Load a PNG file as an SDL2 texture and cache it under the canonical
 * path as the key.  Returns 0 on success, negative errno on failure.
 * On success, the texture is stored in the cache and can be retrieved
 * by the canonical path.
 */
static int load_png(cbx_icon_cache *cache, const char *abs_path,
                    const char *cache_key)
{
    char resolved[PATH_MAX];
    int rc = cbx_icon_validate_path(abs_path, resolved, sizeof(resolved));
    if (rc != 0)
        return rc;

    /* Use SDL2_image to load the image as a surface first, then create a
     * texture from it.  We store the *surface* dimensions (the original
     * image dimensions) rather than the *texture* dimensions, because some
     * SDL renderers create power-of-two textures that differ from the
     * source image size (e.g. an 8x8 PNG becomes a 128x128 texture). */
    SDL_Surface *surface = IMG_Load(resolved);
    if (!surface) {
        fprintf(stderr, "icon_lookup: IMG_Load failed for %s: %s\n",
                resolved, IMG_GetError());
        return -ENOENT;
    }
    int w = surface->w;
    int h = surface->h;

    SDL_Texture *tex = SDL_CreateTextureFromSurface(cache->renderer, surface);
    SDL_FreeSurface(surface);
    if (!tex) {
        fprintf(stderr, "icon_lookup: SDL_CreateTextureFromSurface failed: %s\n",
                SDL_GetError());
        return -ENOENT;
    }

    /* Enable alpha blending. */
    SDL_SetTextureBlendMode(tex, SDL_BLENDMODE_BLEND);

    /* Store in the icon cache using the cache_key (the original path
     * or the canonical path — we use the canonical path for
     * deduplication). */
    rc = cbx_icon_cache_insert(cache, cache_key, tex, w, h);
    if (rc != 0) {
        fprintf(stderr, "icon_lookup: cache full, cannot store %s\n",
                cache_key);
        SDL_DestroyTexture(tex);
        return rc;
    }

    return 0;
}

/* ------------------------------------------------------------------ */
/*  Public API                                                        */
/* ------------------------------------------------------------------ */

int cbx_icon_lookup(cbx_icon_cache *cache, const cbx_icon_map *map,
                    const char *device_type, const char *icon_override,
                    cbx_icon_result *result)
{
    if (!cache || !result)
        return -EINVAL;

    memset(result, 0, sizeof(*result));

    /* Determine the display label and icon name. */
    char icon_name[CBX_ICON_ICON_LEN];
    char display_name[CBX_ICON_NAME_LEN];

    /* First, resolve the display name from the icon map (used for the
     * label regardless of whether an override is present). */
    if (map && device_type && device_type[0] != '\0') {
        cbx_icon_map_lookup(map, device_type,
                            icon_name, sizeof(icon_name),
                            display_name, sizeof(display_name));
    } else {
        /* Unknown/NULL device_type → generic gamepad + raw type. */
        snprintf(icon_name, sizeof(icon_name), "%s", CBX_ICON_DEFAULT_ICON);
        const char *label = (device_type && device_type[0] != '\0')
                            ? device_type : "unknown";
        snprintf(display_name, sizeof(display_name), "%s", label);
    }

    /* Set the label. */
    snprintf(result->label, sizeof(result->label), "%s", display_name);

    /* --- Step 1: Profile icon override (SPEC §8.5) ------------------ */

    if (icon_override && icon_override[0] != '\0') {
        if (icon_override[0] == '/') {
            /* Absolute path → PNG via SDL2_image. */
            /* Check if already cached (by the path itself). */
            SDL_Texture *tex = cbx_icon_cache_get(cache, icon_override);
            if (tex) {
                result->texture = tex;
                cbx_icon_cache_get_dims(cache, icon_override,
                                        &result->width, &result->height);
                return 0;
            }

            /* Load and cache the PNG. */
            int rc = load_png(cache, icon_override, icon_override);
            if (rc == 0) {
                result->texture = cbx_icon_cache_get(cache, icon_override);
                if (result->texture) {
                    cbx_icon_cache_get_dims(cache, icon_override,
                                            &result->width,
                                            &result->height);
                    return 0;
                }
            }
            /* PNG load failed → fall through to device_type lookup. */
        } else {
            /* Built-in icon name override. */
            SDL_Texture *tex = cbx_icon_cache_get(cache, icon_override);
            if (!tex) {
                /* Try to load on demand. */
                int rc = cbx_icon_cache_load_one(cache, icon_override);
                if (rc == 0)
                    tex = cbx_icon_cache_get(cache, icon_override);
            }
            if (tex) {
                result->texture = tex;
                cbx_icon_cache_get_dims(cache, icon_override,
                                        &result->width, &result->height);
                return 0;
            }
            /* Override icon not found → fall through to device_type lookup. */
        }
    }

    /* --- Step 2/3: Icon map lookup (already resolved above) -------- */

    /* Try to get the icon from the cache. */
    SDL_Texture *tex = cbx_icon_cache_get(cache, icon_name);
    if (!tex) {
        /* Try to load on demand. */
        int rc = cbx_icon_cache_load_one(cache, icon_name);
        if (rc == 0)
            tex = cbx_icon_cache_get(cache, icon_name);
    }

    if (tex) {
        result->texture = tex;
        cbx_icon_cache_get_dims(cache, icon_name,
                                &result->width, &result->height);
    }

    /* If we still don't have a texture, try generic-gamepad as a
     * last resort (it should always be available if the cache was
     * loaded from the map). */
    if (!result->texture &&
        strcmp(icon_name, CBX_ICON_DEFAULT_ICON) != 0) {
        tex = cbx_icon_cache_get(cache, CBX_ICON_DEFAULT_ICON);
        if (!tex) {
            int rc = cbx_icon_cache_load_one(cache, CBX_ICON_DEFAULT_ICON);
            if (rc == 0)
                tex = cbx_icon_cache_get(cache, CBX_ICON_DEFAULT_ICON);
        }
        if (tex) {
            result->texture = tex;
            cbx_icon_cache_get_dims(cache, CBX_ICON_DEFAULT_ICON,
                                    &result->width, &result->height);
        }
    }

    return 0;
}