#!/usr/bin/env bash
# Source this script to refresh Ollama Cloud credentials in the caller only.
# Plaintext credentials are never written below the repository.  An operator
# may explicitly persist the generated exports to a protected external FD or
# an external owner-only file.

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(cd -- "$SCRIPT_DIR/../.." && pwd -P)
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
    echo "update-ollama-cookies: source this helper so exports remain in the caller" >&2
    exit 2
fi

fail_update() { echo "update-ollama-cookies: $*" >&2; return 2; }

prompt_secret() {
    local name=$1 label=$2 current input
    current=${!name:-}
    read -r -s -p "$label [${current:+set, hidden}]: " input
    printf '\n'
    [[ -z "$input" ]] || printf -v "$name" '%s' "$input"
    export "${name?}"
}

prompt_value() {
    local name=$1 label=$2 default=$3 current input
    current=${!name:-$default}
    read -r -p "$label [$current]: " input
    printf -v "$name" '%s' "${input:-$current}"
    export "${name?}"
}

emit_exports() {
    printf '# Generated by .factory/tools/update-ollama-cookies.sh\n'
    printf 'export __Secure_session=%q\n' "$__Secure_session"
    printf 'export aid=%q\n' "$aid"
    printf 'export cf_clearance=%q\n' "$cf_clearance"
    printf 'export OLLAMA_THRESHOLD=%q\n' "$OLLAMA_THRESHOLD"
    printf 'export OLLAMA_WAIT_INTERVAL_SECONDS=%q\n' "$OLLAMA_WAIT_INTERVAL_SECONDS"
    printf 'export OLLAMA_WAIT_MAX_SECONDS=%q\n' "$OLLAMA_WAIT_MAX_SECONDS"
    printf 'export OLLAMA_COOKIE=%q\n' "$OLLAMA_COOKIE"
}

# Refuse every repository descendant even when the leaf does not yet exist.
validate_external_path() {
    local requested=$1 parent resolved
    [[ $requested = /* ]] || { fail_update 'OLLAMA_CREDENTIAL_PATH must be absolute'; return 2; }
    parent=$(dirname -- "$requested")
    [[ -d $parent && ! -L $parent ]] || { fail_update 'credential parent must be an existing real directory'; return 2; }
    resolved=$(cd -- "$parent" && pwd -P)/$(basename -- "$requested")
    case "$resolved/" in "$PROJECT_ROOT"/*) fail_update 'credential path must be outside the repository'; return 2 ;; esac
    [[ ! -L $requested ]] || { fail_update 'credential path must not be a symlink'; return 2; }
    printf '%s\n' "$resolved"
}

echo "Updating Ollama usage guard parameters. Press Enter to keep a value."
prompt_secret __Secure_session "__Secure-session"
prompt_secret aid "aid"
prompt_secret cf_clearance "cf_clearance"
prompt_value OLLAMA_THRESHOLD "Usage threshold %" 80
prompt_value OLLAMA_WAIT_INTERVAL_SECONDS "Wait polling interval seconds" 300
prompt_value OLLAMA_WAIT_MAX_SECONDS "Maximum automatic wait seconds (0 = unlimited)" 0

if [[ -z ${__Secure_session:-} || -z ${aid:-} || -z ${cf_clearance:-} ]]; then
    fail_update 'all three cookie values are required'
    return 2
fi

OLLAMA_COOKIE="__Secure-session=${__Secure_session}; aid=${aid}; cf_clearance=${cf_clearance}"
export OLLAMA_COOKIE

if [[ -n ${OLLAMA_CREDENTIAL_FD:-} ]]; then
    [[ $OLLAMA_CREDENTIAL_FD =~ ^[0-9]+$ && -e /proc/$$/fd/$OLLAMA_CREDENTIAL_FD ]] || { fail_update 'OLLAMA_CREDENTIAL_FD is not an open descriptor'; return 2; }
    emit_exports >&"$OLLAMA_CREDENTIAL_FD" || { fail_update 'cannot write protected credential FD'; return 2; }
elif [[ -n ${OLLAMA_CREDENTIAL_PATH:-} ]]; then
    target=$(validate_external_path "$OLLAMA_CREDENTIAL_PATH") || return 2
    old_umask=$(umask); umask 077
    tmp=$(mktemp "$(dirname -- "$target")/.ollama-credentials.XXXXXX") || { umask "$old_umask"; fail_update 'cannot create external credential file'; }
    if ! emit_exports >"$tmp" || ! chmod 600 "$tmp" || ! mv -fT -- "$tmp" "$target"; then
        rm -f -- "$tmp"; umask "$old_umask"; fail_update 'cannot publish external credential file'
    fi
    umask "$old_umask"
    echo "Saved owner-only credentials outside the repository: $target"
else
    echo "Credentials exported to this shell only; no plaintext file was written."
fi

echo "Rotate the Ollama session and Cloudflare credentials after any suspected exposure."
echo "Test with: ./.factory/tools/ollama-usage-guard.sh --check"
