/*
 * config_paths.c — XDG base directory resolution for Controller-Box.
 *
 * Resolves user config and data directories at runtime using XDG env vars
 * with $HOME fallbacks, creates directories with mode 0700 as needed, and
 * provides accessors for compile-time system data paths.
 */
#include "config_paths.h"

/* Generated by CMake: DATA_DIR, ICON_DIR, INPUTPLUMBER_SYSTEM_DATA_DIR. */
#include "config.h"

#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>

#ifndef PATH_MAX
#define PATH_MAX 4096
#endif

/* App-specific subdirectory suffixes appended to XDG base directories. */
#define APP_CONFIG_SUBDIR  "controller-box"
#define IP_PROFILES_SUBDIR  "inputplumber/profiles"

/* XDG fallback paths (relative to $HOME) when XDG_* env vars are unset
 * or not absolute.  Per XDG spec, relative XDG values are ignored. */
#define XDG_CONFIG_FALLBACK ".config"
#define XDG_DATA_FALLBACK   ".local/share"

/* --- Internal helpers ---------------------------------------------------- */

/* Return non-zero if p is an absolute path (starts with '/'). */
static int is_absolute(const char *p)
{
    return p && p[0] == '/';
}

/*
 * Join base + "/" + sub into buf.
 * Returns 0 on success, -ENAMETOOLONG if the result doesn't fit.
 */
static int join_path(char *buf, size_t buf_size, const char *base, const char *sub)
{
    int n = snprintf(buf, buf_size, "%s/%s", base, sub);
    if (n < 0 || (size_t)n >= buf_size)
        return -ENAMETOOLONG;
    return 0;
}

/* --- Public resolution functions ----------------------------------------- */

int cbx_resolve_config_dir(char *buf, size_t buf_size)
{
    const char *xdg = getenv("XDG_CONFIG_HOME");
    if (xdg && xdg[0] != '\0' && is_absolute(xdg))
        return join_path(buf, buf_size, xdg, APP_CONFIG_SUBDIR);

    const char *home = getenv("HOME");
    if (!home || home[0] == '\0')
        return -ENOENT;

    char base[PATH_MAX];
    int rc = join_path(base, sizeof(base), home, XDG_CONFIG_FALLBACK);
    if (rc < 0)
        return rc;
    return join_path(buf, buf_size, base, APP_CONFIG_SUBDIR);
}

int cbx_resolve_user_profiles_dir(char *buf, size_t buf_size)
{
    const char *xdg = getenv("XDG_DATA_HOME");
    if (xdg && xdg[0] != '\0' && is_absolute(xdg))
        return join_path(buf, buf_size, xdg, IP_PROFILES_SUBDIR);

    const char *home = getenv("HOME");
    if (!home || home[0] == '\0')
        return -ENOENT;

    char base[PATH_MAX];
    int rc = join_path(base, sizeof(base), home, XDG_DATA_FALLBACK);
    if (rc < 0)
        return rc;
    return join_path(buf, buf_size, base, IP_PROFILES_SUBDIR);
}

/* --- Directory creation -------------------------------------------------- */

int cbx_ensure_dir(const char *path, mode_t mode)
{
    if (!path || path[0] == '\0')
        return -EINVAL;

    /* Try to create the directory directly. */
    if (mkdir(path, mode) == 0)
        return 0;

    if (errno == EEXIST) {
        struct stat st;
        if (stat(path, &st) == 0 && S_ISDIR(st.st_mode))
            return 0;
        return -ENOTDIR;
    }

    if (errno != ENOENT)
        return -errno;

    /* Parent doesn't exist — find parent and recurse. */
    char parent[PATH_MAX];
    size_t len = strlen(path);
    if (len >= sizeof(parent))
        return -ENAMETOOLONG;
    memcpy(parent, path, len + 1);

    /* Strip trailing slashes (except for root). */
    while (len > 1 && parent[len - 1] == '/')
        parent[--len] = '\0';

    char *slash = strrchr(parent, '/');
    if (!slash)
        return -ENOENT;

    if (slash == parent) {
        /* parent is "/" — root always exists, retry mkdir for path. */
        if (mkdir(path, mode) == 0)
            return 0;
        if (errno == EEXIST) {
            struct stat st;
            if (stat(path, &st) == 0 && S_ISDIR(st.st_mode))
                return 0;
            return -ENOTDIR;
        }
        return -errno;
    }

    *slash = '\0';
    int rc = cbx_ensure_dir(parent, mode);
    if (rc < 0)
        return rc;

    /* Parent now exists — retry creating this directory. */
    if (mkdir(path, mode) == 0)
        return 0;
    if (errno == EEXIST) {
        struct stat st;
        if (stat(path, &st) == 0 && S_ISDIR(st.st_mode))
            return 0;
        return -ENOTDIR;
    }
    return -errno;
}

int cbx_config_dir(char *buf, size_t buf_size)
{
    int rc = cbx_resolve_config_dir(buf, buf_size);
    if (rc < 0)
        return rc;
    return cbx_ensure_dir(buf, 0700);
}

int cbx_user_profiles_dir(char *buf, size_t buf_size)
{
    int rc = cbx_resolve_user_profiles_dir(buf, buf_size);
    if (rc < 0)
        return rc;
    return cbx_ensure_dir(buf, 0700);
}

/* --- System paths (compile-time constants) ------------------------------- */

const char *cbx_system_inputplumber_dir(void)
{
    return INPUTPLUMBER_SYSTEM_DATA_DIR;
}

const char *cbx_system_profiles_dir(void)
{
    return INPUTPLUMBER_SYSTEM_DATA_DIR "/profiles";
}

const char *cbx_system_devices_dir(void)
{
    return INPUTPLUMBER_SYSTEM_DATA_DIR "/devices";
}

const char *cbx_system_capability_maps_dir(void)
{
    return INPUTPLUMBER_SYSTEM_DATA_DIR "/capability_maps";
}

const char *cbx_data_dir(void)
{
    return DATA_DIR;
}

const char *cbx_icon_dir(void)
{
    return ICON_DIR;
}